wandb_version: 1

loss:
  desc: null
  value: null
optim:
  desc: null
  value: null
scheduler:
  desc: null
  value: null
lr:
  desc: null
  value: 0.01
momentum:
  desc: null
  value: 0.9
weight_decay:
  desc: null
  value: 0.0005
resume:
  desc: null
  value: false
epochs:
  desc: null
  value: 100
n_worker:
  desc: null
  value: 16
batch_size:
  desc: null
  value: 256
overall_params:
  desc: null
  value: 1647242
trainable_params:
  desc: null
  value: 1647242
_wandb:
  desc: null
  value:
    python_version: 3.11.2
    cli_version: 0.14.2
    framework: torch
    is_jupyter_run: false
    is_kaggle_kernel: false
    start_time: 1681088727.82997
    t:
      1:
      - 1
      - 41
      - 55
      2:
      - 1
      - 41
      - 55
      3:
      - 2
      - 16
      - 23
      4: 3.11.2
      5: 0.14.2
      8:
      - 5
